server:
  port: 8000
credentials:
  password-hash: "passwordhash"
api:
  callback: "url_endpoint"
spring:
  config:
    location: classpath:/,file:/app/config/
paths: fileOne.json,fileTwo.json
pathSources: fileSourceOne,fileSourceTwo
files:
  discord: path-to-discord.json