server:
  port: 8000
credentials:
  password-hash: "passwordhash"
api:
  callback: "url_endpoint"
spring:
  config:
    location: classpath:/,file:/app/config/
paths: path-to-file.json, path-to-second-file.json