server:
  port: 8000
credentials:
  password-hash: "passwordhash"
api:
  callback: "url_endpoint"
spring:
  config:
    location: classpath:/,file:/app/config/
files:
  discord: ""
paths: fileOne.json,fileTwo.json
pathSources: fileSourceOne,fileSourceTwo
devices: example_lamp
device_operations: toggle/on/off
device_password: device_password
device_ips: device_ip